name: Docker Image CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the appropritely labelled ones
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    services:
      nginx:
       image: nginx
        # Map port 8080 on the Docker host to port 80 on the nginx container
       ports:
        - 8080:80
